spring:
  application:
    name: JobWise
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/jobwise}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  resume:
    upload:
      path: uploads/resumes
    cache:
      ttl-minutes: 30
  servlet:
    multipart: # PDF大小
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  secret: jobWiseSecretKeyForJwt
  expiration: 3600000 # 1 hr in milliseconds
server:
  port: 8080

openai:
  api:
    key: sk-apikey